/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package values;

/**
 *
 * @author dst1
 */
public class values {
    private String BOLGE_ADI;
    private String SUBE_ADI;
    private String MUSTERI_PROFILI;
    private String SEKTOR_KODU;
    private String SEKTOR_ADI;
    private String MUSTERI_SEGMENT_ADI;
    private String RATING_NOTU;
    private String BORCA_DUSME_OLASILIGI;
    private String RATING_GECERLILIK_TARIHI;
    private String KARAR_TARIHI;
    private String VERGI_TOPLAM;
    private String LIMITI_BLOKE_MI;
    private String NAKTI_TOPLAM_RISK;
    private String KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK;
    private String BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM;
    private String KURUMSAL_TOPLAM_RISK;
    private String BIREYSEL_TOPLAM_RISK;
    private String KREDI_KARTI_TOPLAM_RISK;
    private String KREDI_BORCU_ODEME_GUN;
    private String KART_BORCU_GECIKME_TUTARI;
    private String TOPLAM_TAHSILAT_YIL;
    private String MAX_GECIKME_GUN;
    private String TOPLAM_TAHSILAT_AY;
    private String SON_DONEM_ODENMEMIS_KREDI_LIMITI;
    private String ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI;
    private String SON_DONEM_RISK_TOPLAMI;
    private String BIR_ONCEKI_DONEM_RISK_TOPLAMI;
    private String BIR_ONCEKI_DONEM_VERGI_BORCU;
    private String SON_DONEM_NAKDI_RISK_TOPLAMI;
    private String BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI;
    private String SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI;
    private String BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI;
    private String SON_DONEM_LIMIT_DOLULUK_ORANI;
    private String BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI;
    private String TEMINATA_VERDIGI_CEK_TL;
    private String TEMINATA_VERDIGI_CEK_SONUC;
    private String TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI;
    private String BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
    private String BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI;

    public values(String BOLGE_ADI, String SUBE_ADI, String MUSTERI_PROFILI, String SEKTOR_KODU, String SEKTOR_ADI, String MUSTERI_SEGMENT_ADI, String RATING_NOTU, String BORCA_DUSME_OLASILIGI, String RATING_GECERLILIK_TARIHI, String KARAR_TARIHI, String VERGI_TOPLAM, String LIMITI_BLOKE_MI, String NAKTI_TOPLAM_RISK, String KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK, String BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM, String KURUMSAL_TOPLAM_RISK, String BIREYSEL_TOPLAM_RISK, String KREDI_KARTI_TOPLAM_RISK, String KREDI_BORCU_ODEME_GUN, String KART_BORCU_GECIKME_TUTARI, String TOPLAM_TAHSILAT_YIL, String MAX_GECIKME_GUN, String TOPLAM_TAHSILAT_AY, String SON_DONEM_ODENMEMIS_KREDI_LIMITI, String ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI, String SON_DONEM_RISK_TOPLAMI, String BIR_ONCEKI_DONEM_RISK_TOPLAMI, String BIR_ONCEKI_DONEM_VERGI_BORCU, String SON_DONEM_NAKDI_RISK_TOPLAMI, String BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI, String SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI, String BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI, String SON_DONEM_LIMIT_DOLULUK_ORANI, String BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI, String TEMINATA_VERDIGI_CEK_TL, String TEMINATA_VERDIGI_CEK_SONUC, String TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI, String BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI, String BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI, String BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI, String ERKEN_UYARI_NOTU_VAR_MI, String GRUP_EKREN_UYATI_NOTU_VARMII, String MUSTERI_NO, String UZMAN_DEGERLENDIRMESI, String TOPLAM_LIMIT) {
        this.BOLGE_ADI = BOLGE_ADI;
        this.SUBE_ADI = SUBE_ADI;
        this.MUSTERI_PROFILI = MUSTERI_PROFILI;
        this.SEKTOR_KODU = SEKTOR_KODU;
        this.SEKTOR_ADI = SEKTOR_ADI;
        this.MUSTERI_SEGMENT_ADI = MUSTERI_SEGMENT_ADI;
        this.RATING_NOTU = RATING_NOTU;
        this.BORCA_DUSME_OLASILIGI = BORCA_DUSME_OLASILIGI;
        this.RATING_GECERLILIK_TARIHI = RATING_GECERLILIK_TARIHI;
        this.KARAR_TARIHI = KARAR_TARIHI;
        this.VERGI_TOPLAM = VERGI_TOPLAM;
        this.LIMITI_BLOKE_MI = LIMITI_BLOKE_MI;
        this.NAKTI_TOPLAM_RISK = NAKTI_TOPLAM_RISK;
        this.KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK = KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK;
        this.BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM = BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM;
        this.KURUMSAL_TOPLAM_RISK = KURUMSAL_TOPLAM_RISK;
        this.BIREYSEL_TOPLAM_RISK = BIREYSEL_TOPLAM_RISK;
        this.KREDI_KARTI_TOPLAM_RISK = KREDI_KARTI_TOPLAM_RISK;
        this.KREDI_BORCU_ODEME_GUN = KREDI_BORCU_ODEME_GUN;
        this.KART_BORCU_GECIKME_TUTARI = KART_BORCU_GECIKME_TUTARI;
        this.TOPLAM_TAHSILAT_YIL = TOPLAM_TAHSILAT_YIL;
        this.MAX_GECIKME_GUN = MAX_GECIKME_GUN;
        this.TOPLAM_TAHSILAT_AY = TOPLAM_TAHSILAT_AY;
        this.SON_DONEM_ODENMEMIS_KREDI_LIMITI = SON_DONEM_ODENMEMIS_KREDI_LIMITI;
        this.ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI = ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI;
        this.SON_DONEM_RISK_TOPLAMI = SON_DONEM_RISK_TOPLAMI;
        this.BIR_ONCEKI_DONEM_RISK_TOPLAMI = BIR_ONCEKI_DONEM_RISK_TOPLAMI;
        this.BIR_ONCEKI_DONEM_VERGI_BORCU = BIR_ONCEKI_DONEM_VERGI_BORCU;
        this.SON_DONEM_NAKDI_RISK_TOPLAMI = SON_DONEM_NAKDI_RISK_TOPLAMI;
        this.BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI = BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI;
        this.SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI = SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI;
        this.BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI = BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI;
        this.SON_DONEM_LIMIT_DOLULUK_ORANI = SON_DONEM_LIMIT_DOLULUK_ORANI;
        this.BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI = BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI;
        this.TEMINATA_VERDIGI_CEK_TL = TEMINATA_VERDIGI_CEK_TL;
        this.TEMINATA_VERDIGI_CEK_SONUC = TEMINATA_VERDIGI_CEK_SONUC;
        this.TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI = TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI;
        this.BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI = BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
        this.BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI = BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI;
        this.BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI = BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
        this.ERKEN_UYARI_NOTU_VAR_MI = ERKEN_UYARI_NOTU_VAR_MI;
        this.GRUP_EKREN_UYATI_NOTU_VARMII = GRUP_EKREN_UYATI_NOTU_VARMII;
        this.MUSTERI_NO = MUSTERI_NO;
        this.UZMAN_DEGERLENDIRMESI = UZMAN_DEGERLENDIRMESI;
        this.TOPLAM_LIMIT = TOPLAM_LIMIT;
    }

    public String getBOLGE_ADI() {
        return BOLGE_ADI;
    }

    public void setBOLGE_ADI(String BOLGE_ADI) {
        this.BOLGE_ADI = BOLGE_ADI;
    }

    public String getSUBE_ADI() {
        return SUBE_ADI;
    }

    public void setSUBE_ADI(String SUBE_ADI) {
        this.SUBE_ADI = SUBE_ADI;
    }

    public String getMUSTERI_PROFILI() {
        return MUSTERI_PROFILI;
    }

    public void setMUSTERI_PROFILI(String MUSTERI_PROFILI) {
        this.MUSTERI_PROFILI = MUSTERI_PROFILI;
    }

    public String getSEKTOR_KODU() {
        return SEKTOR_KODU;
    }

    public void setSEKTOR_KODU(String SEKTOR_KODU) {
        this.SEKTOR_KODU = SEKTOR_KODU;
    }

    public String getSEKTOR_ADI() {
        return SEKTOR_ADI;
    }

    public void setSEKTOR_ADI(String SEKTOR_ADI) {
        this.SEKTOR_ADI = SEKTOR_ADI;
    }

    public String getMUSTERI_SEGMENT_ADI() {
        return MUSTERI_SEGMENT_ADI;
    }

    public void setMUSTERI_SEGMENT_ADI(String MUSTERI_SEGMENT_ADI) {
        this.MUSTERI_SEGMENT_ADI = MUSTERI_SEGMENT_ADI;
    }

    public String getRATING_NOTU() {
        return RATING_NOTU;
    }

    public void setRATING_NOTU(String RATING_NOTU) {
        this.RATING_NOTU = RATING_NOTU;
    }

    public String getBORCA_DUSME_OLASILIGI() {
        return BORCA_DUSME_OLASILIGI;
    }

    public void setBORCA_DUSME_OLASILIGI(String BORCA_DUSME_OLASILIGI) {
        this.BORCA_DUSME_OLASILIGI = BORCA_DUSME_OLASILIGI;
    }

    public String getRATING_GECERLILIK_TARIHI() {
        return RATING_GECERLILIK_TARIHI;
    }

    public void setRATING_GECERLILIK_TARIHI(String RATING_GECERLILIK_TARIHI) {
        this.RATING_GECERLILIK_TARIHI = RATING_GECERLILIK_TARIHI;
    }

    public String getKARAR_TARIHI() {
        return KARAR_TARIHI;
    }

    public void setKARAR_TARIHI(String KARAR_TARIHI) {
        this.KARAR_TARIHI = KARAR_TARIHI;
    }

    public String getVERGI_TOPLAM() {
        return VERGI_TOPLAM;
    }

    public void setVERGI_TOPLAM(String VERGI_TOPLAM) {
        this.VERGI_TOPLAM = VERGI_TOPLAM;
    }

    public String getLIMITI_BLOKE_MI() {
        return LIMITI_BLOKE_MI;
    }

    public void setLIMITI_BLOKE_MI(String LIMITI_BLOKE_MI) {
        this.LIMITI_BLOKE_MI = LIMITI_BLOKE_MI;
    }

    public String getNAKTI_TOPLAM_RISK() {
        return NAKTI_TOPLAM_RISK;
    }

    public void setNAKTI_TOPLAM_RISK(String NAKTI_TOPLAM_RISK) {
        this.NAKTI_TOPLAM_RISK = NAKTI_TOPLAM_RISK;
    }

    public String getKURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK() {
        return KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK;
    }

    public void setKURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK(String KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK) {
        this.KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK = KURUMSAL_GAYRINAKDI_TOPLAM_ANA_PARA_RISK;
    }

    public String getBIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM() {
        return BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM;
    }

    public void setBIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM(String BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM) {
        this.BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM = BIREYSEL_VE_KURUMSAL_VE_KREDI_KARTI_RISK_TOPLAM;
    }

    public String getKURUMSAL_TOPLAM_RISK() {
        return KURUMSAL_TOPLAM_RISK;
    }

    public void setKURUMSAL_TOPLAM_RISK(String KURUMSAL_TOPLAM_RISK) {
        this.KURUMSAL_TOPLAM_RISK = KURUMSAL_TOPLAM_RISK;
    }

    public String getBIREYSEL_TOPLAM_RISK() {
        return BIREYSEL_TOPLAM_RISK;
    }

    public void setBIREYSEL_TOPLAM_RISK(String BIREYSEL_TOPLAM_RISK) {
        this.BIREYSEL_TOPLAM_RISK = BIREYSEL_TOPLAM_RISK;
    }

    public String getKREDI_KARTI_TOPLAM_RISK() {
        return KREDI_KARTI_TOPLAM_RISK;
    }

    public void setKREDI_KARTI_TOPLAM_RISK(String KREDI_KARTI_TOPLAM_RISK) {
        this.KREDI_KARTI_TOPLAM_RISK = KREDI_KARTI_TOPLAM_RISK;
    }

    public String getKREDI_BORCU_ODEME_GUN() {
        return KREDI_BORCU_ODEME_GUN;
    }

    public void setKREDI_BORCU_ODEME_GUN(String KREDI_BORCU_ODEME_GUN) {
        this.KREDI_BORCU_ODEME_GUN = KREDI_BORCU_ODEME_GUN;
    }

    public String getKART_BORCU_GECIKME_TUTARI() {
        return KART_BORCU_GECIKME_TUTARI;
    }

    public void setKART_BORCU_GECIKME_TUTARI(String KART_BORCU_GECIKME_TUTARI) {
        this.KART_BORCU_GECIKME_TUTARI = KART_BORCU_GECIKME_TUTARI;
    }

    public String getTOPLAM_TAHSILAT_YIL() {
        return TOPLAM_TAHSILAT_YIL;
    }

    public void setTOPLAM_TAHSILAT_YIL(String TOPLAM_TAHSILAT_YIL) {
        this.TOPLAM_TAHSILAT_YIL = TOPLAM_TAHSILAT_YIL;
    }

    public String getMAX_GECIKME_GUN() {
        return MAX_GECIKME_GUN;
    }

    public void setMAX_GECIKME_GUN(String MAX_GECIKME_GUN) {
        this.MAX_GECIKME_GUN = MAX_GECIKME_GUN;
    }

    public String getTOPLAM_TAHSILAT_AY() {
        return TOPLAM_TAHSILAT_AY;
    }

    public void setTOPLAM_TAHSILAT_AY(String TOPLAM_TAHSILAT_AY) {
        this.TOPLAM_TAHSILAT_AY = TOPLAM_TAHSILAT_AY;
    }

    public String getSON_DONEM_ODENMEMIS_KREDI_LIMITI() {
        return SON_DONEM_ODENMEMIS_KREDI_LIMITI;
    }

    public void setSON_DONEM_ODENMEMIS_KREDI_LIMITI(String SON_DONEM_ODENMEMIS_KREDI_LIMITI) {
        this.SON_DONEM_ODENMEMIS_KREDI_LIMITI = SON_DONEM_ODENMEMIS_KREDI_LIMITI;
    }

    public String getONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI() {
        return ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI;
    }

    public void setONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI(String ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI) {
        this.ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI = ONCEKI_DONEM_ODENMEMIS_KREDI_LIMITI;
    }

    public String getSON_DONEM_RISK_TOPLAMI() {
        return SON_DONEM_RISK_TOPLAMI;
    }

    public void setSON_DONEM_RISK_TOPLAMI(String SON_DONEM_RISK_TOPLAMI) {
        this.SON_DONEM_RISK_TOPLAMI = SON_DONEM_RISK_TOPLAMI;
    }

    public String getBIR_ONCEKI_DONEM_RISK_TOPLAMI() {
        return BIR_ONCEKI_DONEM_RISK_TOPLAMI;
    }

    public void setBIR_ONCEKI_DONEM_RISK_TOPLAMI(String BIR_ONCEKI_DONEM_RISK_TOPLAMI) {
        this.BIR_ONCEKI_DONEM_RISK_TOPLAMI = BIR_ONCEKI_DONEM_RISK_TOPLAMI;
    }

    public String getBIR_ONCEKI_DONEM_VERGI_BORCU() {
        return BIR_ONCEKI_DONEM_VERGI_BORCU;
    }

    public void setBIR_ONCEKI_DONEM_VERGI_BORCU(String BIR_ONCEKI_DONEM_VERGI_BORCU) {
        this.BIR_ONCEKI_DONEM_VERGI_BORCU = BIR_ONCEKI_DONEM_VERGI_BORCU;
    }

    public String getSON_DONEM_NAKDI_RISK_TOPLAMI() {
        return SON_DONEM_NAKDI_RISK_TOPLAMI;
    }

    public void setSON_DONEM_NAKDI_RISK_TOPLAMI(String SON_DONEM_NAKDI_RISK_TOPLAMI) {
        this.SON_DONEM_NAKDI_RISK_TOPLAMI = SON_DONEM_NAKDI_RISK_TOPLAMI;
    }

    public String getBIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI() {
        return BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI;
    }

    public void setBIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI(String BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI) {
        this.BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI = BIR_ONCEKI_DONEM_NAKTI_RISK_TOPLAMI;
    }

    public String getSON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI() {
        return SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI;
    }

    public void setSON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI(String SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI) {
        this.SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI = SON_DONEM_GAYRI_NAKTI_RISK_TOPLAMI;
    }

    public String getBIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI() {
        return BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI;
    }

    public void setBIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI(String BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI) {
        this.BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI = BIR_ONCEKI_GAYRI_NAKTI_RISK_TOPLAMI;
    }

    public String getSON_DONEM_LIMIT_DOLULUK_ORANI() {
        return SON_DONEM_LIMIT_DOLULUK_ORANI;
    }

    public void setSON_DONEM_LIMIT_DOLULUK_ORANI(String SON_DONEM_LIMIT_DOLULUK_ORANI) {
        this.SON_DONEM_LIMIT_DOLULUK_ORANI = SON_DONEM_LIMIT_DOLULUK_ORANI;
    }

    public String getBIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI() {
        return BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI;
    }

    public void setBIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI(String BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI) {
        this.BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI = BIR_ONCEKI_DONEM_LIMIT_DOLULUK_ORANI;
    }

    public String getTEMINATA_VERDIGI_CEK_TL() {
        return TEMINATA_VERDIGI_CEK_TL;
    }

    public void setTEMINATA_VERDIGI_CEK_TL(String TEMINATA_VERDIGI_CEK_TL) {
        this.TEMINATA_VERDIGI_CEK_TL = TEMINATA_VERDIGI_CEK_TL;
    }

    public String getTEMINATA_VERDIGI_CEK_SONUC() {
        return TEMINATA_VERDIGI_CEK_SONUC;
    }

    public void setTEMINATA_VERDIGI_CEK_SONUC(String TEMINATA_VERDIGI_CEK_SONUC) {
        this.TEMINATA_VERDIGI_CEK_SONUC = TEMINATA_VERDIGI_CEK_SONUC;
    }

    public String getTEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI() {
        return TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI;
    }

    public void setTEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI(String TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI) {
        this.TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI = TEMINATA_ALINMIS_CEKLERIN_TAHSIL_ORANI;
    }

    public String getBIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI() {
        return BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
    }

    public void setBIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI(String BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI) {
        this.BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI = BIR_YIL_ONCESI_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
    }

    public String getBIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI() {
        return BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI;
    }

    public void setBIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI(String BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI) {
        this.BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI = BIR_YIL_ONCESI_ICRA_KAYDI_VAR_MI;
    }

    public String getBU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI() {
        return BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
    }

    public void setBU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI(String BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI) {
        this.BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI = BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
    }

    public String getERKEN_UYARI_NOTU_VAR_MI() {
        return ERKEN_UYARI_NOTU_VAR_MI;
    }

    public void setERKEN_UYARI_NOTU_VAR_MI(String ERKEN_UYARI_NOTU_VAR_MI) {
        this.ERKEN_UYARI_NOTU_VAR_MI = ERKEN_UYARI_NOTU_VAR_MI;
    }

    public String getGRUP_EKREN_UYATI_NOTU_VARMII() {
        return GRUP_EKREN_UYATI_NOTU_VARMII;
    }

    public void setGRUP_EKREN_UYATI_NOTU_VARMII(String GRUP_EKREN_UYATI_NOTU_VARMII) {
        this.GRUP_EKREN_UYATI_NOTU_VARMII = GRUP_EKREN_UYATI_NOTU_VARMII;
    }

    public String getMUSTERI_NO() {
        return MUSTERI_NO;
    }

    public void setMUSTERI_NO(String MUSTERI_NO) {
        this.MUSTERI_NO = MUSTERI_NO;
    }

    public String getUZMAN_DEGERLENDIRMESI() {
        return UZMAN_DEGERLENDIRMESI;
    }

    public void setUZMAN_DEGERLENDIRMESI(String UZMAN_DEGERLENDIRMESI) {
        this.UZMAN_DEGERLENDIRMESI = UZMAN_DEGERLENDIRMESI;
    }

    public String getTOPLAM_LIMIT() {
        return TOPLAM_LIMIT;
    }

    public void setTOPLAM_LIMIT(String TOPLAM_LIMIT) {
        this.TOPLAM_LIMIT = TOPLAM_LIMIT;
    }
    private String BU_YIL_KARSICILIKSIZ_CEK_KAYDI_VAR_MI;
    private String ERKEN_UYARI_NOTU_VAR_MI;
    private String GRUP_EKREN_UYATI_NOTU_VARMII;
    private String MUSTERI_NO;
    private String UZMAN_DEGERLENDIRMESI;
    private String TOPLAM_LIMIT;
}
